name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-repo-structure:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking repo structure"
      - run: python3 scripts/CheckRepoStructure.py
