name: TXT
on:
  pull_request:
    branches: [main]
jobs:
  update-txt-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: echo "Updating txt files"
      - run: python3 scripts/UpdateTxtFiles.py
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git add .
      - run: git commit -m "generated"
      - run: git push
